name:                rocksdb-haskell-bindings
version:             0.1.0.0
github:              "daleiz/rocksdb-haskell-bindings"
license:             BSD3
author:              "Wang Bin"
maintainer:          "wangbin@emqx.com"
copyright:           "Wang Bin"

tested-with:         GHC == 8.10.2, GHC == 8.8.4, GHC == 8.6.5

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/daleiz/haskell-rocksdb-bindings#readme>

dependencies:
- base >= 4.7 && < 5
- resourcet
- transformers
- either
- bytestring
- conduit
- streamly >= 0.7 && < 1
- data-default
- binary

library:
  source-dirs: src
  build-tools: c2hs
  extra-libraries: rocksdb

tests:
  rocksdb-haskell-bindings-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rocksdb-haskell-bindings
    - hspec
    - temporary-resourcet
